# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 400)
        font = QtGui.QFont("Arial" , 16)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, 0, 351, 50))
        self.label_result.setStyleSheet(
            "background-color: rgb(201, 230, 255);")
        self.label_result.setObjectName("label_result")
        self.label_result.setFont(font)
        self.btn_devide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_devide.setGeometry(QtCore.QRect(270, 310, 81, 91))
        self.btn_devide.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_devide.setObjectName("btn_devide")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(0, 310, 91, 91))
        self.btn_0.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_0.setObjectName("btn_0")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(90, 310, 181, 91))
        self.btn_equal.setStyleSheet("background-color: rgb(255, 136, 0);")
        self.btn_equal.setObjectName("btn_equal")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(180, 220, 91, 91))
        self.btn_3.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_3.setObjectName("btn_3")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 220, 91, 91))
        self.btn_1.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(90, 220, 91, 91))
        self.btn_2.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_2.setObjectName("btn_2")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(180, 130, 91, 91))
        self.btn_6.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_6.setObjectName("btn_6")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(90, 130, 91, 91))
        self.btn_5.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_5.setObjectName("btn_5")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(0, 130, 91, 91))
        self.btn_4.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_4.setObjectName("btn_4")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(90, 40, 91, 91))
        self.btn_8.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_8.setObjectName("btn_8")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 40, 91, 91))
        self.btn_7.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_7.setObjectName("btn_7")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(180, 40, 91, 91))
        self.btn_9.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_9.setObjectName("btn_9")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(270, 220, 81, 91))
        self.btn_mult.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_mult.setObjectName("btn_mult")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(270, 130, 81, 91))
        self.btn_minus.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(270, 40, 81, 91))
        self.btn_plus.setStyleSheet("\n"
"background-color: rgb(255, 202, 10);")
        self.btn_plus.setObjectName("btn_plus")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.answ = False
        self.set_actions()
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.btn_devide.setText(_translate("MainWindow", "/"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_plus.setText(_translate("MainWindow", "+"))

    def set_actions(self):
                self.btn_0.clicked.connect(lambda: self.numb_click_action(self.btn_0.text()))
                self.btn_1.clicked.connect(lambda: self.numb_click_action(self.btn_1.text()))
                self.btn_2.clicked.connect(lambda: self.numb_click_action(self.btn_2.text()))
                self.btn_3.clicked.connect(lambda: self.numb_click_action(self.btn_3.text()))
                self.btn_4.clicked.connect(lambda: self.numb_click_action(self.btn_4.text()))
                self.btn_5.clicked.connect(lambda: self.numb_click_action(self.btn_5.text()))
                self.btn_6.clicked.connect(lambda: self.numb_click_action(self.btn_6.text()))
                self.btn_7.clicked.connect(lambda: self.numb_click_action(self.btn_7.text()))
                self.btn_8.clicked.connect(lambda: self.numb_click_action(self.btn_8.text()))
                self.btn_9.clicked.connect(lambda: self.numb_click_action(self.btn_9.text()))
                self.btn_plus.clicked.connect(lambda: self.numb_click_action(self.btn_plus.text()))
                self.btn_minus.clicked.connect(lambda: self.numb_click_action(self.btn_minus.text()))
                self.btn_mult.clicked.connect(lambda: self.numb_click_action(self.btn_mult.text()))
                self.btn_devide.clicked.connect(lambda: self.numb_click_action(self.btn_devide.text()))

                self.btn_equal.clicked.connect(self.answer)

    def numb_click_action(self, number):
                if self.answ == True:
                       self.label_result.setText('')
                       self.answ = False
                       if self.label_result.text() == "0":
                                self.label_result.setText(number)
                       else:
                                self.label_result.setText(self.label_result.text() + str(number))
                else:
                       if self.label_result.text() == "0":
                                self.label_result.setText(number)
                       else:
                                self.label_result.setText(self.label_result.text() + str(number))
    def answer(self):
           self.answ = True
           self.label_result.setText(f'Answer: {eval(self.label_result.text())}')
           
    def errors(self):
           error = QMessageBox()
           error.setIcon(QMessageBox.warning)
           error.setWindowTitle("Warning!")
           error.setText("Unexpected Error!")
           error.setStandardButtons(QMessageBox)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
